name: psycho-i
channels:
  - conda-forge
dependencies:
  - "python>=3.9"
  - numpy
  - "matplotlib==3.4"
  - freetype
  - "pkg-config==0.29.2"
  - "libpng==1.6.39"
  - mypy
  - pip
  - h5py
  - "pytest>=7.0"
  - "nox>=7.0"
  - "pre-commit>=2.20.0"
  - "numba>=0.56.0"
  - "sphinx>=4.0"
  - "sphinxcontrib-napoleon"
  - "myst-parser"
