name: psycho-i
channels:
  - conda-forge
dependencies:
  - "python>=3.7"
  - numpy
  - matplotlib
  - mypy
  - pip
  - "pytest>=7.0"
  - "nox>=7.0"
  - "pre-commit>=2.20.0"
  - "numba>=0.56.0"
  - "sphinx>=4.0"
  - "sphinxcontrib-napoleon"